---
- hosts: dbservers
  tasks:
    - name: Install MYSQL databas
      action: apt pkg={{ item }} state=latest
	with_items:
         - libmysqlclient-dev
         - python-mysqldb
         - mysql-server
         - mysql-client

    - name: Start the MYSQL service
      action: service name=mysql state=started

    - name: Create database user 'deploy' with password and all database privileges and 'WITH GRANT OPTION'
      mysql_user: 
       user='deploy' password=password host='%' priv=*.*:ALL,GRANT
       
    - name: Ensure anonymous users are not in the database
      mysql_user: 
       user='' host={{ item }} state=absent
      with_items:
       - 127.0.0.1
       - ::1
       - localhost
     
    - name: Update mysql root password for all root accounts
      mysql_user:
       name=root host={{ item }} password=password
      with_items:
       - 127.0.0.1
       - ::1
       - localhost
